title: Home
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.

exclude:
  - .sass-cache

sass:
  sass_dir: css
  style: compressed
